export const SYSTEM_SETTING_KEYS = {
  GOOGLE_API_KEY: "GOOGLE_API_KEY",
  GOOGLE_CLIENT_ID: "GOOGLE_CLIENT_ID",
  GOOGLE_CLIENT_SECRET: "GOOGLE_CLIENT_SECRET",
  GOOGLE_REFRESH_TOKEN: "GOOGLE_REFRESH_TOKEN",
  YANDEX_API_KEY: "YANDEX_API_KEY",
  YANDEX_VENDOR_API_KEY: "YANDEX_VENDOR_API_KEY",
  YANDEX_VENDOR_BUSINESS_ID: "YANDEX_VENDOR_BUSINESS_ID",
  YANDEX_EDA_COOKIE: "YANDEX_EDA_COOKIE",
  YANDEX_EDA_OAUTH: "YANDEX_EDA_OAUTH",
  YANDEX_EDA_PARTNER_ID: "YANDEX_EDA_PARTNER_ID",
  UZUM_COOKIE: "UZUM_COOKIE",
  UZUM_TOKEN: "UZUM_TOKEN",
  UZUM_MERCHANT_ID: "UZUM_MERCHANT_ID",
  DGIS_API_KEY: "DGIS_API_KEY",
  TELEGRAM_BOT_TOKEN: "TELEGRAM_BOT_TOKEN",
  TELEGRAM_CHAT_ID: "TELEGRAM_CHAT_ID",
  SYNC_INTERVAL_MINUTES: "SYNC_INTERVAL_MINUTES",
  GEMINI_API_KEY: "GEMINI_API_KEY",
};

export const REVIEW_SOURCES = {
  GOOGLE_MAPS: "GOOGLE_MAPS",
  YANDEX_MAPS: "YANDEX_MAPS",
  YANDEX_VENDOR: "YANDEX_VENDOR",
  DGIS: "DGIS",
  UZUM_VENDOR: "UZUM_VENDOR",
} as const;

export type ReviewSourceType = keyof typeof REVIEW_SOURCES;
